apiVersion: v1
kind: Secret
metadata:
  name: manager-bootstrap-credentials
  namespace: system
type: Opaque
data:
  token: '${SAKURACLOUD_B64ENCODED_TOKEN}'
  secret: '${SAKURACLOUD_B64ENCODED_SECRET}'

