
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: sakuracloudclusters.infrastructure.cluster.x-k8s.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.zone
    description: name of the SakuraCloud zone
    name: Zone
    type: string
  - JSONPath: .status.sourceArchive.name
    description: name of the source archive
    name: Archive
    type: string
  group: infrastructure.cluster.x-k8s.io
  names:
    categories:
    - cluster-api
    kind: SakuraCloudCluster
    listKind: SakuraCloudClusterList
    plural: sakuracloudclusters
    singular: sakuracloudcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SakuraCloudCluster is the Schema for the sakuracloudclusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SakuraCloudClusterSpec defines the desired state of SakuraCloudCluster
          properties:
            cloudProviderConfiguration:
              description: "SakuraCloudProviderConfig is the Schema for the SakurCloudControllerManger
                configuration \n TODO 要修正"
              properties:
                accessSecret:
                  description: AccessSecret .
                  type: string
                accessToken:
                  description: AccessToken .
                  type: string
                clusterID:
                  description: ClusterID .
                  type: string
                image:
                  description: Image .
                  type: string
                zone:
                  description: Zone .
                  type: string
              type: object
            zone:
              type: string
          required:
          - zone
          type: object
        status:
          description: SakuraCloudClusterStatus defines the observed state of SakuraCloudClusterSpec
          properties:
            apiEndpoints:
              description: APIEndpoints represents the endpoints to communicate with
                the control plane.
              items:
                description: APIEndpoint represents a reachable Kubernetes API endpoint.
                properties:
                  host:
                    description: The hostname on which the API server is serving.
                    type: string
                  port:
                    description: The port on which the API server is serving.
                    type: integer
                required:
                - host
                - port
                type: object
              type: array
            errorMessage:
              description: "ErrorMessage will be set in the event that there is a
                terminal problem reconciling the Machine and will contain a more verbose
                string suitable for logging and human consumption. \n This field should
                not be set for transitive errors that a controller faces that are
                expected to be fixed automatically over time (like service outages),
                but instead indicate that something is fundamentally wrong with the
                Machine's spec or the configuration of the controller, and that manual
                intervention is required. Examples of terminal errors would be invalid
                combinations of settings in the spec, values that are unsupported
                by the controller, or the responsible controller itself being critically
                misconfigured. \n Any transient errors that occur during the reconciliation
                of Machines can be added as events to the Machine object and/or logged
                in the controller's output."
              type: string
            errorReason:
              description: "ErrorReason will be set in the event that there is a terminal
                problem reconciling the Machine and will contain a succinct value
                suitable for machine interpretation. \n This field should not be set
                for transitive errors that a controller faces that are expected to
                be fixed automatically over time (like service outages), but instead
                indicate that something is fundamentally wrong with the Machine's
                spec or the configuration of the controller, and that manual intervention
                is required. Examples of terminal errors would be invalid combinations
                of settings in the spec, values that are unsupported by the controller,
                or the responsible controller itself being critically misconfigured.
                \n Any transient errors that occur during the reconciliation of Machines
                can be added as events to the Machine object and/or logged in the
                controller's output."
              type: string
            ready:
              type: boolean
          required:
          - ready
          type: object
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
