
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: sakuracloudmachines.infrastructure.cluster.x-k8s.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.cpus
    description: number of CPUs
    name: CPUs
    type: integer
  - JSONPath: .spec.memoryGB
    description: size of memory
    name: Memory
    type: integer
  - JSONPath: .spec.diskGB
    description: size of the disks
    name: Disk
    type: integer
  - JSONPath: .status.state
    description: current status of the machine
    name: Status
    type: string
  group: infrastructure.cluster.x-k8s.io
  names:
    categories:
    - cluster-api
    kind: SakuraCloudMachine
    listKind: SakuraCloudMachineList
    plural: sakuracloudmachines
    singular: sakuracloudmachine
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SakuraCloudMachine is the Schema for the sakuracloudmachines API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SakuraCloudMachineSpec defines the desired state of SakuraCloudMachine
          properties:
            cpus:
              description: CPUs is the number of virtual processors in a virtual machine.
                Defaults to the analogue property value in the template from which
                this machine is cloned.
              type: integer
            diskGB:
              description: DiskGiB is the size of a virtual machine's disk, in GB.
              type: integer
            machineRef:
              description: This value is set automatically at runtime and should not
                be set or modified by users. MachineRef is used to lookup the VM.
              properties:
                filters:
                  description: "Filters is a set of key/value pairs used to identify
                    a resource They are applied according to the rules defined by
                    the SakuraCloud API: https://developer.sakura.ad.jp/cloud/api/1.1/
                    \n If SakuraCloud API with Filters returns multiple results, it
                    use first data of results"
                  items:
                    description: Filter is a filter used to identify an SakuraCloud
                      resource
                    properties:
                      name:
                        description: Name of the filter. Filter names are case-sensitive.
                        type: string
                      values:
                        description: Values includes one or more filter values. Filter
                          values are case-sensitive.
                        items:
                          type: string
                        type: array
                    required:
                    - name
                    - values
                    type: object
                  type: array
                id:
                  description: ID of resource
                  type: string
              type: object
            memoryGB:
              description: MemoryMiB is the size of a virtual machine's memory, in
                GB.
              type: integer
            providerID:
              description: ProviderID is the unique identifier as specified by the
                cloud provider.
              type: string
            sourceArchive:
              description: SourceArchive .
              properties:
                filters:
                  description: "Filters is a set of key/value pairs used to identify
                    a resource They are applied according to the rules defined by
                    the SakuraCloud API: https://developer.sakura.ad.jp/cloud/api/1.1/
                    \n If SakuraCloud API with Filters returns multiple results, it
                    use first data of results"
                  items:
                    description: Filter is a filter used to identify an SakuraCloud
                      resource
                    properties:
                      name:
                        description: Name of the filter. Filter names are case-sensitive.
                        type: string
                      values:
                        description: Values includes one or more filter values. Filter
                          values are case-sensitive.
                        items:
                          type: string
                        type: array
                    required:
                    - name
                    - values
                    type: object
                  type: array
                id:
                  description: ID of resource
                  type: string
              type: object
          required:
          - sourceArchive
          type: object
        status:
          description: SakuraCloudMachineStatus defines the observed state of SakuraCloudMachine
          properties:
            addresses:
              description: Addresses contains the SakuraCloud instance associated
                addresses.
              items:
                description: NodeAddress contains information for the node's address.
                properties:
                  address:
                    description: The node address.
                    type: string
                  type:
                    description: Node address type, one of Hostname, ExternalIP or
                      InternalIP.
                    type: string
                required:
                - address
                - type
                type: object
              type: array
            errorMessage:
              description: "ErrorMessage will be set in the event that there is a
                terminal problem reconciling the Machine and will contain a more verbose
                string suitable for logging and human consumption. \n This field should
                not be set for transitive errors that a controller faces that are
                expected to be fixed automatically over time (like service outages),
                but instead indicate that something is fundamentally wrong with the
                Machine's spec or the configuration of the controller, and that manual
                intervention is required. Examples of terminal errors would be invalid
                combinations of settings in the spec, values that are unsupported
                by the controller, or the responsible controller itself being critically
                misconfigured. \n Any transient errors that occur during the reconciliation
                of Machines can be added as events to the Machine object and/or logged
                in the controller's output."
              type: string
            errorReason:
              description: "ErrorReason will be set in the event that there is a terminal
                problem reconciling the Machine and will contain a succinct value
                suitable for machine interpretation. \n This field should not be set
                for transitive errors that a controller faces that are expected to
                be fixed automatically over time (like service outages), but instead
                indicate that something is fundamentally wrong with the Machine's
                spec or the configuration of the controller, and that manual intervention
                is required. Examples of terminal errors would be invalid combinations
                of settings in the spec, values that are unsupported by the controller,
                or the responsible controller itself being critically misconfigured.
                \n Any transient errors that occur during the reconciliation of Machines
                can be added as events to the Machine object and/or logged in the
                controller's output."
              type: string
            jobRef:
              description: JobRef is a managed object reference to a Job related to
                the SakuraCloud resources. This value is set automatically at runtime
                and should not be set or modified by users.
              type: string
            ready:
              description: Ready is true when the provider resource is ready.
              type: boolean
            sourceArchive:
              description: "SourceArchiveInfo represents information of the node template
                image \n This value is set automatically at runtime and should not
                be set or modified by users."
              properties:
                id:
                  description: ID .
                  type: string
                name:
                  description: Name .
                  type: string
              type: object
            state:
              description: State is the state of the SakuraCloud instance for this
                machine.
              type: string
          type: object
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
